### PR TITLE
chirp/drivers/kenwood_live.py add language encoding for latin

### PR DESCRIPTION
**Pull request by ephemer0l**
I needed this for a Kenwood 2000X programming it on Gentoo

### CODE REVIEW

**Comment by mpoletiek** [comment]
Can you help me understand how this doesn't interfere with other languages?

Thanks,

**Comment by ephemer0l** [comment]
I think bug #18 is related.
I don't have experience with other languages, so I cant say, but it was needed for a TS-2000X. I have a TH-F6A, TH-D72, TH-and TH-D700A I've yet to update programming on. I'll eventually test those, too.

**Comment by ephemer0l** [comment]
Also, just noticed you're a fellow Gentoo'er I updated the ebuild from pentoo that I helped contribute to in my own [ephemer0l-overlay/net-wireless/chirp/](https://github.com/ephemer0l/ephemer0l-overlay/blob/master/net-wireless/chirp/chirp-20210821.ebuild)  for my ebuilds. I updated the suds dep to reflect the current new package name. The snapshots are from your repo, the live is the old broken py2 version from upstream.

**Comment by mpoletiek** [comment]
Apologies, but this repo is not maintained.

**Pull request closed without merging**
